// This file is automatically generated. Do not modify it.
import type { FirebaseOptions } from 'firebase/app';

/**
 * The Firebase project's configuration object.
 *
 * This object is used to initialize the Firebase app. It is pulled from the
 * Firebase CLI when the project is initialized.
 */
export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyCN6TywBh86nQ_OtNf3mZtAyFoLHX0Vvjg",
  authDomain: "locate-ai-a5391.firebaseapp.com",
  projectId: "locate-ai-a5391",
  storageBucket: "locate-ai-a5391.appspot.com",
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
  appId: "YOUR_APP_ID",
};
