// This file is automatically generated. Do not modify it.
// See the side effect in `src/firebase/index.ts` to learn more.
import { FirebaseOptions, initializeApp } from 'firebase/app';

/**
 * The Firebase project's configuration object.
 *
 * This object is used to initialize the Firebase app. It is pulled from the
 * Firebase CLI when the project is initialized.
 */
const firebaseConfig: FirebaseOptions = {
  apiKey: "YOUR_API_KEY",
  authDomain: "YOUR_AUTH_DOMAIN",
  projectId: "locate-ai-a5391",
  storageBucket: "YOUR_STORAGE_BUCKET",
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
  appId: "YOUR_APP_ID",
};

/**
 * Initializes the Firebase app and returns the app object.
 *
 * This function is idempotent, meaning it can be called multiple times without
 * creating a new app each time.
 *
 * @returns The initialized Firebase app object.
 */
export function initializeFirebaseApp() {
  return initializeApp(firebaseConfig);
}
